### ISSUE TITLE
Multiple origins not supported

### ISSUE THREAD

**Issue by puigru** [alfonsocv12/bottle-cors-plugin#2]
The documentation says to use the following to allow several origins:
```
cors_plugin(['google.com', 'youtube.com'])
```
However, this is not actually implemented. The plugins just treats the list as a string and the header becomes:
```
Access-Control-Allow-Origin: ['google.com', 'youtube.com']
```
The plugin should check if the Origin header matches any of the allowed origins and if it does use that.

**Comment by alfonsocv12** [comment]
Hi sorry for the delays covid, my job and last semester of school went hard on me hope you still use the library
